""" WALLETTTUPDATED cryptouserreferral 2

Revision ID: 0a73228ca798
Revises: fa93cc2f8cc2
Create Date: 2025-04-30 09:05:38.869927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a73228ca798'
down_revision: Union[str, None] = 'fa93cc2f8cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
