""" WALLETTTUPDATED token coinnnn balllance

Revision ID: 0ec3efeb7c8e
Revises: bb09e8025299
Create Date: 2025-05-04 07:38:02.574718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec3efeb7c8e'
down_revision: Union[str, None] = 'bb09e8025299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
