""" ride prices

Revision ID: 3960c2f5c806
Revises: 8328700d22e6
Create Date: 2025-03-29 21:00:28.021116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3960c2f5c806'
down_revision: Union[str, None] = '8328700d22e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('vip_price', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('standard_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'standard_price')
    op.drop_column('rides', 'vip_price')
    # ### end Alembic commands ###
