""" WALLETTTUPDATED token coinn balance

Revision ID: 6f9ecff9deef
Revises: d09a6eb72779
Create Date: 2025-05-02 05:00:04.063004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9ecff9deef'
down_revision: Union[str, None] = 'd09a6eb72779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_coin_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'coin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('coin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_coin_id_fkey', 'transactions', 'coins', ['coin_id'], ['id'])
    # ### end Alembic commands ###
