""" WALLETTTUPDATED

Revision ID: 737afa41c040
Revises: eb36087d1b50
Create Date: 2025-04-29 18:56:46.837206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737afa41c040'
down_revision: Union[str, None] = 'eb36087d1b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_index(op.f('ix_crypto_users_id'), 'crypto_users', ['id'], unique=False)
    op.create_table('token_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crypto_user_id', sa.Integer(), nullable=True),
    sa.Column('token_symbol', sa.Enum('TRX', 'USDT', 'USDC', 'BTC', 'ETH', name='tokensymbol'), nullable=True),
    sa.Column('public_address', sa.String(), nullable=False),
    sa.Column('private_key_encrypted', sa.String(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_user_id'], ['crypto_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_wallets_id'), 'token_wallets', ['id'], unique=False)
    op.add_column('wallets', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('wallets', sa.Column('crypto_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wallets', 'crypto_users', ['crypto_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'crypto_user_id')
    op.drop_column('wallets', 'currency')
    op.drop_index(op.f('ix_token_wallets_id'), table_name='token_wallets')
    op.drop_table('token_wallets')
    op.drop_index(op.f('ix_crypto_users_id'), table_name='crypto_users')
    op.drop_table('crypto_users')
    # ### end Alembic commands ###
