"""Add Coin and WalletCoinBalance models

Revision ID: 7f8b58298076
Revises: 3ba6b32a4469
Create Date: 2025-04-27 08:29:16.715302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8b58298076'
down_revision: Union[str, None] = '3ba6b32a4469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
