""" WALLETTTUPDATED cryptouserreferral

Revision ID: 8241e169f219
Revises: 0664256140df
Create Date: 2025-04-29 23:08:55.831207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8241e169f219'
down_revision: Union[str, None] = '0664256140df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_users', sa.Column('referral_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_users', 'referral_code')
    # ### end Alembic commands ###
