""" WALLETTTUPDATED token coinnnn balance

Revision ID: bb09e8025299
Revises: 6f9ecff9deef
Create Date: 2025-05-02 05:32:25.817955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb09e8025299'
down_revision: Union[str, None] = '6f9ecff9deef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('coin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'coins', ['coin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'coin_id')
    # ### end Alembic commands ###
