""" WALLETTTUPDATED token balance

Revision ID: d09a6eb72779
Revises: 0a73228ca798
Create Date: 2025-05-01 07:49:23.744179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd09a6eb72779'
down_revision: Union[str, None] = '0a73228ca798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_wallets', sa.Column('balance', sa.Float(), nullable=True))
    op.alter_column('token_wallets', 'token_symbol',
               existing_type=postgresql.ENUM('TRX', 'USDT', 'USDC', 'BTC', 'ETH', name='tokensymbol'),
               type_=sa.String(),
               nullable=False)
    op.add_column('transactions', sa.Column('token_wallet_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('recipient_address', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'token_wallets', ['token_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'recipient_address')
    op.drop_column('transactions', 'token_wallet_id')
    op.alter_column('token_wallets', 'token_symbol',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TRX', 'USDT', 'USDC', 'BTC', 'ETH', name='tokensymbol'),
               nullable=True)
    op.drop_column('token_wallets', 'balance')
    # ### end Alembic commands ###
