""" WALLETTTUPDATED address

Revision ID: fa93cc2f8cc2
Revises: 8241e169f219
Create Date: 2025-04-30 08:32:32.348585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa93cc2f8cc2'
down_revision: Union[str, None] = '8241e169f219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_users', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('crypto_users', sa.Column('secret_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'crypto_users', ['public_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crypto_users', type_='unique')
    op.drop_column('crypto_users', 'secret_key')
    op.drop_column('crypto_users', 'public_key')
    # ### end Alembic commands ###
